LICENSE
Makefile
Makefile.inc
src/cmsg.c
src/cmsg.h
src/config.h
src/conmon.c

Did a little Makefile workery as well.
Signed-off-by: baude <bbaude@redhat.com>

Initial code checking from crio

---

contrib/spec/conmon.spec.in

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@baude @rhatdan

contrib/spec: initial rpm spec file addition

---

src/conmon.c

Update Conmon from CRI-O master branch

---

.cirrus.yml

Signed-off-by: Chris Evich <cevich@redhat.com>

Fix CRI-O repo. references and image names

---

Makefile
src/conmon.c
src/ctr_logging.c
src/ctr_logging.h
src/utils.c
src/utils.h

c/conmon has fallen quite behind upstream cri-o. Let's catch up :)

Update to cri-o

---

.cirrus.yml
contrib/cirrus/integration_test.sh
contrib/cirrus/lib.sh
contrib/cirrus/packer/Makefile
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/setup_environment.sh
contrib/cirrus/spoof_travis.patch

... or at least test enabling it

Enable fedora integration testing

---

src/utils.c
src/utils.h

journald logging broke debugging print to syslog, and this PR finishes fixing it

fix silly syslog error

---

src/conmon.c

Add support for OOM handling when running in cgroup v2 unified mode.
Wait for notifications using inotify on the
/sys/fs/cgroup/$PATH/memory.events file.
On an inotify event read the "oom" counter from the same file.
Create an "oom" file each time the counter is different than the
previous known value.
Closes: https://github.com/containers/conmon/issues/8

conmon: support OOM monitor under cgroup v2

---

LICENSE

Update license to have owners and date of copyright

---

LICENSE

remove appendix

---

Makefile

Use configurable make variable for pkg-config

---

src/conmon.c
src/ctr_logging.c
src/utils.c
src/utils.h

report here: https://lgtm.com/projects/g/containers/conmon
Afterwards, we can enable LGTM for each PR.

fix issues reported by lgtm.com

---

README.md

README.md: add LGTM.com badge

---

install.md

fixes https://github.com/containers/conmon/issues/58

add installation guide

---

src/conmon.c

fix a race with Podman restart where it tries to bind ports
immediately after the exit file was created.

conmon: close FDs before creating exit file

---

Makefile

Closes #32.
I've added a `dockerized` target for convenience as well.
Signed-off-by: Max Goltzsche <max.goltzsche@gmail.com>

Add static & dockerized targets to Makefile.

---

cmd/conmon-config/conmon-config.go
runner/config/config.go
src/config.h
src/conmon.c

instead of having a note that says to sync the value

Add CONN_SOCK_BUF_SIZE to config

---

src/conmon.c

before calling the exit command be sure the sync pipe is closed so
that the waiting process can stop waiting.
It solves an issue with Podman where the cleanup process could hang
since the container is already locked by the podman process waiting
on the sync pipe.  The reproducer here:
podman --runtime /bin/false run --rm  alpine true

conmon: close the sync pipe before exit command

---

src/conmon.c

Write the exit files under the container bundle directory so
they are available even when we restart the node. Also, keeping
it scoped there makes the cleanup easier.
Also, we hardlink this file to the exit directory location
used for inotify.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Write exit file to container persistent directory

---

src/conmon.c

fixes: https://github.com/containers/conmon/pull/97#issuecomment-565065081

persist oom files on cgroup v2

---

src/conmon.c

This reverts commit 4100fb20bc156fdd602f8684affa27e6b139d0ad.
We found issues where the reading of the memory control file was racing with the cgroup manager's write. while we want to prevent false positives, not having false negatives is more important. Revert this commit until we find a more complete solution.

Revert "conmon: check oom counter on cgroup v1"

---

cmd/conmon-config/conmon-config.go
runner/config/config.go
src/config.h
src/conmon.c

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Add TimedOutMessage to config to share with go code

---

src/ctr_logging.c

We should never flush the buffer because we have control of what we're putting in, but calls to writev() require a valid fd. This isn't a problem in runtime, but static code checks flag it. Fix it by writing to /dev/null
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1780892

journal logging: write to /dev/null instead of -1

---

src/conmon.c

This PR is a replacement for https://github.com/containers/conmon/commit/4100fb20bc156fdd602f8684affa27e6b139d0ad, in which we verify an OOM occured when we get triggered on the eventfd.
When we check for an oom, there are three cases we must worry about:
1. the cgroup OOM'd
2. the cgroup was destroyed
3. the cgroup OOM'd and was destroyed
We have always handled case 1 (when we get an oom, the eventfd gets an events, we write the oom file)
For case two, we need to check to see if the cgroup.memory_control file exists. We are pretty sure if this file doesn't exist, and this is the first event we've received on the fd, the cgroup was cleaned up instead of an oom happening. This also matches what containerd does.
the third case is when we're not sure about the second case. If both an oom and …

oom v1: verify cgroup hasn't been cleaned up

---

src/conmon.c

There exists an opportunity for a race between checking the eventfd for events, and checking that the cgroup exists. Specifically:
if we read the eventfd before the cgroup is destroyed, but check that the cgroup exists after its destroyed, we will miss a real oom (because the first event triggered was an oom)
To mitigate this, we need to check the existance of the file before we read the event. Since the kernel first removes the files, then triggers an event, we resolve the race here

oom: fix potential race between verification steps

---

src/ctr_exit.h
src/ctr_logging.c
src/utils.h

two tweaks I've noticed while working on a diffent issue.

some minor cleanups

---

README.md

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

[README.md] Update crun URL to https://github.com/containers/crun

---

src/cli.h
src/ctr_stdio.h

include stdint to compile with alpine3.11

---

src/conmon.c
src/conn_sock.c
src/conn_sock.h
src/ctr_stdio.c
src/ctrl.c
src/globals.c
src/globals.h

We want to remove the master/slave terminology from our
code and make it more inclusive.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Fix slave/master termonology

---

Containerfile
Makefile

I liked the idea from the podman repo to build stuff inside a container. It keeps the host clean. So tried to reproduce it for this repo as well. Have a look and let me know if you like it.

Use Podman for building

---

nix/default.nix

nix: remove double definition for e2fsprogs

---

README.md
contrib/cirrus/README.md
hack/get_ci_vm.sh
src/ctr_stdio.c

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Fix problems found by codespell

---

src/conn_sock.c

the age of symlinking the attach socket to generate the sunpath must end.
The path is simply too long, and it is quite hacky anyway.
when setting up the attach socket, chdir to the directory before linking the sunpath.
That allows us to drop this age old hack, and future proof the code
fixes: https://github.com/containers/conmon/issues/213

attach: always chdir

---

src/conmon.c

should fix https://bugzilla.redhat.com/show_bug.cgi?id=1893567

set locale to inherit environment

---

docs/Makefile

fix propagation of PREFIX variable to docs/Makefile

---

src/conn_sock.c

src: avoid unuseful strdup

---

.github/workflows/integration.yml
hack/github-actions-setup
src/close_fds.c

This adds a GitHub action for integration testing the latest CRI-O
master against the conmon change to verify its impact.

Add CRI-O integration test GitHub action

---

src/conn_sock.c

fixes https://github.com/containers/conmon/issues/251

conn_sock: fix potential segfault

---

.cirrus.yml

It seems these tasks are not using more then 1 CPU

Use less resources

---

.github/workflows/integration.yml

fix gh action yaml

---

src/ctr_exit.c

staying as subreaper means the exit command would not be able to start new daemonizes processes e.g. another podman container if it's been set to restart.
Fixes: 4d3dba9c4beb ("exit: fix race zombie reaper")
Fixes: https://github.com/containers/podman/issues/12635
I'm not 100% happy with this fix as written in the comment, it means we could still leak some process so #290 might come back... Unfortunately I don't see much other way about it: going back to reaping existing children and waiting only for the exact pid of the exit command as was done previously is just as bad, this is somewhere in between.
Anyway, I'm just mostly happy I finally figured why the double-fork didn't work, feel free to suggest other solutions.

exit_command: unset subreaper attribute before running exit command

---

.github/workflows/integration.yml
hack/kubernetes-e2e

ci: bump to go 1.17

---

src/conn_sock.c
src/ctrl.c
src/seccomp_notify.c

as they're more debug logs than info

drop some logs to debug level

---

src/ctr_logging.c

journald: print tag and name if both are specified

---

.github/workflows/integration.yml
hack/github-actions-setup

bump golang in gh action to 1.18

---

.packit.yaml

This commit will run Copr builds on every PR against all active
releases of Fedora, thus allowing buildability checks before the
PR merges.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
EDIT: s/Koji scratch/Copr/

Packit: initial enablement

---

src/ctr_logging.c

Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

don't leak syslog_identifier

---

src/ctrl.c

Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

ctrl: drop fifo perms to 0660

---

.github/workflows/integration.yml

Ref: https://go.dev/blog/go1.21

gh actions: bump to go 1.21

---

src/cgroup.c
src/conn_sock.c
src/oom.c

so they are not propagated to the children.

src: open all files with O_CLOEXEC

---

README.md

Correct the conmon Nix channel information to fix search error "Wrong channel selected!".

README.md: update the correct Nix channel

---

.cirrus.yml

Remove CI VM OS names

---

hack/github-actions-setup

Imported from https://github.com/cri-o/cri-o/blob/release-1.31/scripts/github-actions-packages

Install some packages to fix CI

---

src/ctr_stdio.c

Handle descriptor in non-blocking mode properly.

---

src/cmsg.c
src/ctr_logging.c
src/ctr_stdio.c
src/ctrl.c
src/oom.c
src/utils.h

I was looking into how conmon logs things and found out a few things that can be improved, so here's this.
Please review commit by commit; see individual commits for details.

Logging fixups and cleanups

---

src/conn_sock.c
src/utils.h

Introduce pwarnf() for better diagnosis of socket/fd write issues.

---

meson.build

Fix meson install path to match Makefile
