.papr.yml
.rpmbuild/Makefile
.rpmbuild/prepare.sh
contrib/spec/conmon.spec.in

Test conmon binary build on Fedora 28 in a container.  Then make a SRPM from
the current source tree and rpmbuild it.  Finally, verify it installs cleanly
and the packaging worked.
Signed-off-by: baude <bbaude@redhat.com>

Initial PAPR CI check-in

---

meson.build

Replace the rules in a Makefile with a Meson based build.
The build is essentially equivalent, except that the target directory for the conmon binary is `$(LIBEXECDIR)/podman` instead of `$(LIBEXECDIR)/crio`.
---
This is in some ways an alternative to #9 (even though merging both is probably fine.)
Getting it right on Makefiles is just too hard... Meson is much nicer. (If using `make`, at least adopting automake would make the Makefiles more reliable, but Meson is still a much cleaner approach!)
This is somewhat incomplete, since the `.rpmbuild/Makefile` and `*.spec.in` need updating, and the change needs a counterpart in the Fedora RPM for podman... But let me know your initial thoughts, I'd be happy to update those as well if you like the idea of adopting Meson.
Cheers,
Filipe

Add Meson build configuration

---

.clang-format
Makefile

This PR adds the .clang-format file to the repository, which
includes all available Options based on the style from the CRI-O
repository.

Add .clang-format file

---

Makefile
Makefile.inc

The git commands leads into annoying failures when not running within a
git repository (only on downloaded sources). It should be fine to remove
them since they're not used anywhere.

Remove Makefile git shell commands

---

Makefile

Hey there, I saw a warning on the CRI-O conmon project and thought it would be nice to build with `-Werror` in the future, WDYT?

Update build flags to include -Werror

---

src/conmon.c

We now add a warning if the read of events fd failed. This also fixes a warning that the return value of `read` is not considered in that place.

Add warning if read events failed

---

.cirrus.yml
Makefile
contrib/cirrus/lib.sh
contrib/spec/conmon.spec.in

Users can now directly install to a "podman" directory, instead of needing to install to crio, then link to podman

Add podman and crio make target

---

Makefile

Build systems that specify PREFIX typically do not include
the DESTDIR value.
So, the DESTDIR value should be used independently to ensure
that it is used at all.

fix: separate DESTDIR variable from PREFIX

---

.cirrus.yml
.gitignore
Makefile
cmd/conmon-config/conmon-config.go
hack/tree_status.sh
runner/config/config.go
runner/config/config_unix.go
runner/config/config_windows.go

Now, we can configure conmon from within the conmon directory.
This will allow tools to vendor conmon and import the values they need, rather than having the configuration parameters in different repositories
This PR also comes with the eventual goal of coupling containers/conmon with the go code that calls it, so libraries that use conmon don't have to worry too much about conflicting versions

Add cmd/config/config.go

---

src/conmon.c

before we attempt to create the attach socket, make sure it doesn't
already exist otherwise bind(2) will fail with EEXIST.
Closes: https://github.com/containers/libpod/issues/3381

conmon: force unlink attach socket

---

contrib/cirrus/lib.sh
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/setup_environment.sh
src/conmon.c

Change the conmon -e endpoint to optionally take a --attach option, as well as an attach_sync_fd. This allows us to attach to an exec session with conmon
Also attempt to change CI to build from CRI-O master instead of the latest release on the fedora (needed to actually merge this into libpod in a timely manner)

Conmon exec

---

src/conmon.c

There were two errors that weren't specified as coming from conmon
Fixes: https://github.com/containers/conmon/issues/53

prefix logging with conmon:

---

Makefile

If the `git` executable is not available then the `git-vars` Makefile
target will now cover that as well.
Side-port of: https://github.com/cri-o/cri-o/pull/2581

Update git-vars target to check for executable as well

---

src/conmon.c

always check it is a valid PID before passing it down to kill(2).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1730919

conmon: check it is valid pid before kill'ing it

---

src/conmon.c
src/utils.h

at exit propagate the return code from the watched container.  This is
useful when running in systemd so it can properly detect a failure and
restart the container if necessary.

conmon: propagate error code from the container

---

src/conmon.c

This fixes the missing field initializers error when compiling with
clang:
```
> make CC=clang
src/conmon.c:119:7: error: missing field 'short_name' initializer
{NULL}};
^
```

Fix compilation with clang

---

Makefile

Do not fail when calling the clean target without building first.
Signed-off-by: Stefan Agner <stefan@agner.ch>

Makefile: don't fail if clean is called without a build

---

src/conmon.c

exec with conmon ran into issues because the manager attempted to resize the window before stdout was configured. Thus, we got the ctrl_cb from the caller, but had no where to send the ioctl.
Fix this by registering the callback after we set stdout.

set masterfd_stdout before regsitering ctrl_cb

---

.cirrus.yml

This PR adds the static binary build to the CI to ensure that everything works as expected.

Add static binary build to Cirrus CI

---

src/utils.c
src/utils.h

The trace log level is currently not supported by conmon, but seems to be
a valid level for container runtimes like CRI-O and podman. This results
that the container currently won't start if the log level is set to
'trace'. Beside this, we now case insensitively compare the log level
string to make it more fail safe.

Add 'trace' log level support

---

src/conmon.c
src/ctr_logging.c
src/ctr_logging.h
src/utils.c
src/utils.h

it specifies an additional tag to use for logging messages.
When using journald, it adds a tag "CONTAINER_TAG".

src: add new option --log-tag

---

cmd/conmon-config/conmon-config.go
runner/config/config.go
src/config.h
src/conmon.c

The terminal_ctrl_fd was being overloaded with events. CRI-O wants to reopen the log files at any time, and podman wants to not drop window resize events on exec.
But we can have both.
Introduce winsz_fd_*, a special fifo pair for window resize events. The terminal_ctrl passes window resize events to the write side, and the read side can process them (after masterfd_stdout is initialized, so we have somewhere to write to and we don't drop events).
Also, add ctrl event types to conmon config

 Handle window resize events in a different fifo 

---

src/conmon.c

This way, when an error occurs in the attach endpoint logic, conmon can exit immediately without having to clean up the child process. Because the exit happens before forking, the child process doesn't have to be cleaned up at all.
This doesn't solve the core problem that no cleanup is being done on exit but after looking into the code making sure everything is cleanup up correctly is a bit out of my league and is better done by someone more familiar with the code. 
As an aside (and this is absolutely not meant in a bad way), I found the code rather hard to understand with the massive single conmon.c file with very a large main function, lots of globals/callbacks and no clearly defined point of cleanup. I was also expecting a lot more inline documentation on what conmon does and how its …

Initialize the endpoint for attach before calling fork.

---

src/conmon.c

inotify fails with EINVAL when trying to read an event with a too
small buffer.
Increase the size to "sizeof(struct inotify_event) + NAME_MAX + 1",
that is enough to read at least one event.
Closes: https://github.com/containers/conmon/issues/87

conmon: fix tight loop on OOM

---

src/conmon.c

when the timeout is expired, instead of killing the process, make sure
to kill the entire process group.
It is not safe as using pid cgroup or a pid namespace, which we cannot
use as the script must run inside of the container pid namespace, but
it addresses most common cases like bash forking a new process.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1774184

conmon: kill the process group on timeout

---

src/conmon.c

We want to ensure we save the oom file as well for reboot scenario.
@giuseppe @haircommander PTAL.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Persist the oom file when --persist-dir is specified

---

src/conmon.c

when running on cgroup v1, also check whether the OOM counter is > 0
before writing the "oom" file.
Previously, conmon was detecting an OOM every time an event fd was
triggered.
Unfortunately that is not enough, as an event on the eventfd is also
triggered when the cgroup is deleted.  That could cause a race
condition where conmon sees the event from the cgroup deletion before
the SIGCHLD+SIGUSR1.  That could happen for example when systemd
CollectMode is set for failed units.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1782601

conmon: check oom counter on cgroup v1

---

src/conmon.c

the first advantage is that it is much faster as data is not copied
from the kernel to the userspace and the back to the kernel, and the
second advantage is that we don't block on writ'ing on the fd all the
data we've buffered.
Closes: https://github.com/containers/conmon/issues/99

conmon: use splice(2) to copy from stdin

---

src/conmon.c

%10s just ensures that when printing, at least 10 characters are
written. However, in this case we probably want *at most* 10 characters
to be written.

Fixes format string to limit the size of the string to 10 characters

---

src/conmon.c

make sure every user inside of the container can use the standard
files.  Without the chmod, only root in the container would be able to
print to stdout.
It went unnoticed with runc, as runc itself corrects these permissions
but it should not be the OCI runtime responsibility since conmon is
creating these files.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786449

conmon: chmod std files pipes

---

src/ctr_logging.c

k8s-file doesn't support --log-tag so raise an error when they are
used together.

log: reject --log-tag with k8s-file

---

src/conmon.c

before, we only adjusted the score to -999. This was to prevent a memory leak in conmon from preventing it from being killed.
Luckily, conmon is perfect and would never leak memory.
But actually, conmon being OOM killed is *very* bad, and even possibly allowing it leads to funky situations where it's killed before a process that really should be (the container its watching).
In CRI-O, we attempted to mitigate this issue by creating conmonmon, a conmon monitoring thread, but that lead us to incorrectly report OOMs (where an unordered tear down of a cgroup would render conmon killed before the container, and conmonmon would interpret that as an OOM)
This leaves us with no better choice (for now) other than declaring conmon should never be OOM killed. Future work exists for better OOM …

bump oom adjust score to -1000

---

src/conmon.c

As discussed in #123, there's a race condition where it's possible to get to this point with `timed_out` true and the process already dead (and `container_pid` already cleared). That has rather negative consequences (`kill(-1, SIGKILL)` as root).
Since the container exited on its own, it seems like we should just ignore the timeout and treat it like a normal container exit.
Fixes #123
Signed-off-by: Andrew Drake <andrew@frontapp.com>

Ignore timeout if container process is already dead.

---

src/conmon.c

in the event of a non-terminal, api v1 exec session, we need to run the main_loop a second time to make sure we get all output from the i/o pipes connected to the container.
However, occasionally, the container process will finish before this main loop is called. We catch it when we check the child processes immediately preceeding the g_main_loop_run, but that gives no way to exit the main loop (as we've already removed container_exit_cb as a source.
The solution here is to exit the main loop if we get to stdio_cb, the first i/o pipe has been closed (either stderr or stdout, doesn't matter the order), and we know the container_status. this allows us to read all the i/o, but still properly exit conmon
fixes: https://github.com/containers/libpod/issues/5339
assuming that …

stdio: sometimes quit main loop after io is done

---

.dir-locals.el
src/conmon.c

splice(2) doesn't seem to handle correctly sockets having a type of SOCK_SEQPACKET.
When using a SOCK_SEQPACKET, each read is limited to the current packet.  The data that doesn't fit in a single read(2) call will be discarded.  This can be a problem when the fd_out doesn't accept all the data, so on a short write we lose the data that could not be written by the splice(2) call.
Replace splice(2) with splitting the read/write loop.

conmon: drop usage of splice(2)

---

src/cgroup.c
src/cli.c
src/conmon.c
src/conn_sock.c
src/ctr_exit.c
src/ctr_logging.c
src/ctrl.c
src/parent_pipe_fd.c
src/runtime_args.c
src/utils.c
src/utils.h

we already mandate C99, and I find code is easier to read when a variable is declared when its needed

style: stop declaring variables at top of block

---

src/utils.h

as it's needed for strerror
fixes https://github.com/containers/conmon/issues/136

utils: include string

---

src/cli.c
src/cli.h
src/conmon.c
src/utils.c
src/utils.h

a major drawback of conmon's double forking model is the parent loses stderr after the fork. This makes debugging challenging.
Add --output-file, allowing the caller to specify a file to write conmon's logs to. Eventually, all container engines should use this option instead of the default `stderr`

WIP: add --output-file

---

src/conmon.c
src/ctr_exit.c
src/ctr_exit.h

store each termination status reported to us while waiting for the container PID file to be created.
Once we know the container PID we check in the cache whether we already know the status.

conmon: store status while waiting for pid

---

install.md

Provide additional installation options by using Ansible with https://github.com/alvistack/ansible-role-conmon from source code.
Fixes #142

Add Installation Guide with Ansible

---

Makefile
src/conn_sock.c
src/conn_sock.h
src/ctrl.c

if there was any data already received, make sure it is flushed to the tty as soon as it is opened.
Closes: https://github.com/containers/libpod/issues/4397

tty: flush pending data when fd is ready

---

src/cli.c
src/cli.h
src/ctr_exit.c

This is inspired by a need to periodically reap exec sessions within Podman. When launched from the HTTP API, exec sessions must persist for some amount of time after they exit (Docker runs a reaper every 5 minutes, marking inactive sessions and then removing sessions that are already marked on a subsequent run).
Rather than doing this in Podman, which does not have a daemon, it seems logical to leverage Conmon. We're already using Conmon's exit command infrastructure to clean up detached exec sessions, so it's not much of a stretch to use it for this. The change itself is quite simple (new argument to set a delay, and then a sleep before the exit command is invoked).

Add option to delay execution of exit command

---

.gitignore
Makefile
nix/default.nix
nix/nixpkgs.json
nix/nixpkgs.nix

Switching from the current static build to a nix based derivation.
Similar PR will go for crun/conmon/libpod/etc, too.
Also see
- ~~https://github.com/containers/crun/pull/372~~
- https://github.com/containers/conmon/pull/161
- https://github.com/containers/libpod/pull/6402
Fixes #156
P.S. conmon-v2.0.17 with nix-based binary could be found from https://github.com/alvistack/conmon/releases/tag/v2.0.17

Add nix derivation for static builds

---

nix/default.nix
nix/nixpkgs.json

Using `conmon.overrideAttrs` may result as broken due to nixpkgs upstream changes; replace with native `stdenv.mkDerivation` with complete definition could simply avoid this happening.
Changes based on https://github.com/NixOS/nixpkgs/blob/e469b77/pkgs/applications/virtualization/conmon/default.nix; also fix `conmon --version` with correct version and commit, e.g.
```
conmon version 2.0.17
commit: 6be2eb8bb24fc403183ad5186a381ae61151b372
```
Fixes #168
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

[nix] Use `stdenv.mkDerivation` instead of `conmon.overrideAttrs`

---

src/ctrl.c

ctrl: warn if we fail to unlink

---

src/ctr_logging.c

When conmon writes a field with the incorrect length, it is not displayed correctly by journalctl. that can make it seem like the CONTAINER_NAME field is not being added, when in reality it's not formatted correctly.

journald: fix logging container name

---

runner/conmon/options.go
runner/conmon_test/conmon_test.go
src/ctr_logging.c

When using strtok, you cannot tell if the original string had a : or not, because with
with "journald" you get driver = "journald" and path = NULL
with "journald:" you get driver = "journald" and path = NULL
That means invalid: writes to a file invalid, instead of throwing an error.
Similarly, when passing none or none: we make sure no file is written to disk.
Add debugging output for logdriver diagnostics and use in unit tests.
And "" and : just segfault.
All fixed now.

Update log-path parsing and unit-tests to handle a lot more edge cases.

---

src/ctr_exit.c

This was first noticed when running Podman when using the exit command delay functionality. When the OCI runtime exits with an error, there are some cases where Conmon will exit without reaping it; thus, we were ending up with a zombie that persisted until the exit command completed and exited. We didn't notice this before because the exit command only took a second or two so the zombie's lifetime was very short, since it would reparent and be reaped once Conmon died. With exit-delay, though, we could be leaving a zombie around for hundreds of seconds, and this means we cannot kill the container during this period.

Reap PIDs before running exit command

---

src/conmon.c
src/ctr_logging.c

on a crash, CRI-O completely wipes out the entire storage so there is
no need on syncing the log files.

conmon: drop fsync calls

---

.cirrus.yml
Makefile
nix/default.nix
nix/nixpkgs.json

@saschagrunert Once I update with `make nixpkgs` for https://github.com/containers/conmon/releases/tag/v2.0.18, I found the compile with `nix build -f nix/` will failed as below:
```
builder for '/nix/store/yvrx4c696ahd3xnf92111a66ddys9i93-gnutls-3.6.14.drv' failed with exit code 2; last 10 log lines:
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:2184: certtool] Error 1
make[4]: Leaving directory '/tmp/nix-build-gnutls-3.6.14.drv-0/gnutls-3.6.14/src'
make[3]: *** [Makefile:2383: all-recursive] Error 1
make[3]: Leaving directory '/tmp/nix-build-gnutls-3.6.14.drv-0/gnutls-3.6.14/src'
make[2]: *** [Makefile:2044: all] Error 2
make[2]: Leaving directory '/tmp/nix-build-gnutls-3.6.14.drv-0/gnutls-3.6.14/src'
make[1]: *** [Makefile:1757: all-recursive] Error 1
make[1]: …
```

nix run -f channel:nixos-20.03

---

README.md
src/cli.c
src/cli.h
src/conmon.c
src/ctr_exit.c
src/ctr_exit.h
src/utils.h

This includes:
unconditionally reap children as it doesn't hurt, and we've seen cases where the children are not cleaned up after a clean exit (causing excess load for systemd)
add --sync to allow conmon to only fork once, allowing the caller to have fewer children
also, make sure we don't call atexit callbacks for failed children after fork() by replacing calls to pexit() with _pexit()

add options to handle children differently

---

src/cli.c
src/cli.h
src/conmon.c
src/ctr_logging.c

this allows callers to keep backward compatibility (if they rely on the sync) but new users to drop the sync if they'd like

logs: readd sync, but gate behavior on cli flag

---

nix/default.nix

This removes additional tests from e2fsprogs which fail on some local
machines.
Closes #192 
@haircommander PTAL if this fixes the build issue on your machine.

Fix nix build for failing e2fsprogs tests

---

.cirrus.yml
nix/default.nix
nix/nixpkgs.json

Also see:
- https://github.com/containers/crun/pull/428
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2428
- https://github.com/containers/podman/pull/7076
- https://github.com/cri-o/cri-o/pull/4012
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

Speedup static build by utilizing CI cache on `/nix` folder

---

cmd/conmon-config/conmon-config.go

`fmt.Errorf` returns a result which has not being used in
conmon-config.go before this patch. We now `log.Fatal` the error to
actually report to the user that config generation has been failed.

Fail if conmon config could not be written

---

Makefile

This commit adds the -g option to generate debug information.
Resolves: rhbz#1786090
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@haircommander @giuseppe @saschagrunert PTAL

Makefile: enable debuginfo generation

---

src/conmon.c

if kill is passed a process that is less than -1, it kills every pid in the process group.
However, if it is passed -1, then conmon attempts to kill everything it can
protect against the case that getpgid returns a 1

protect against kill(-1)

---

.cirrus.yml
nix/default.nix
nix/nixpkgs.json

Backport changes from https://github.com/cri-o/cri-o/pull/4065/files#diff-1d37e48f9ceff6d8030570cd36286a61R189-R197
Also update systemd 246 as per https://github.com/NixOS/nixpkgs/pull/94354
Fix #206
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

Update nix pin with `make nixpkgs`

---

src/cli.c
src/cli.h
src/conmon.c
src/conn_sock.c
src/conn_sock.h
src/ctr_stdio.c
src/globals.c
src/globals.h

Refactored all the conn_sock functionality to be more generic. It can deal
with different types of sockets, stream vs dgram, and reuses all the same
callbacks, shutdown and async functionality.
Conmon creates a notify socket which podman bind-mounts into the container,
and passes in via the spec's environment variables.  Conmon relays the
READY=1 signal.  This is similar to what runc and crun do, but doing it in
conmon and NOT passing NOTIFY_SOCKET to the OCI runtime allows us to start
up properly without runc and crun blocking on the "start" command.
It would also be trivial to add more proxied sockets, i.e. the /dev/log
proof of concept I did would now be super easy, if we wanted to revisit that.
Signed-off-by: Joseph Gooch <mrwizard@dok.org>

Refactor I/O and add SD_NOTIFY proxy support

---

src/conn_sock.c

GCC does not complain about the variable here being unused, but clang
does:
../src/conn_sock.c:134:23: error: unused variable 'symlink_dir_path' [-Werror,-Wunused-variable]
_cleanup_free_ char *symlink_dir_path =
^
1 error generated.

conn_sock: Explicitly free a heap-allocated string

---

src/conn_sock.c

we already have code in place to handle partial writes, just make sure
the fd is not blocking so it doesn't hang on writes.
Closes: https://github.com/containers/conmon/issues/204

conn_sock: make dest fd non blocking

---

src/cli.c
src/cli.h
src/conn_sock.c

unfortunately, older podman versions rely on conmon truncating the unix socket length when setting up the attach socket.
Introduce a flag to gate the changed behavior, allowing newer podman versions to be able to handle longer UID in rootless mode,
but also allowing older podman versions to work.

conn_sock: add chdir-attach option

---

src/cli.c
src/conn_sock.c

I must admit I didn't test correctly, and there were two regressions with the previous commit on conn_sock.
1: sock_fullpath doesn't exist at the time that we need to copy its location into sun_path. As such, we need to use the proc entry of the parent dir, and use that as the parent path.
2: we do need the symlink to the bundle_path, as that's where the attach file actually lives.

conn_sock: fix path opening

---

src/conn_sock.c

commit 6287bd884d9bf29e76ac877e0c7e6aad04bc24a4 introduced the
regression.
writes to the attached sockets must be blocking, otherwise the
write_back_to_remote_consoles() shutdowns the socket when write fails
with EAGAIN.
I've verified the original issue fixed with commit 62887bd is not
reintroduced with this patch.
Closes: https://github.com/containers/conmon/issues/236

conn_sock: do not fail on EAGAIN

---

.cirrus.yml
nix/default-arm64.nix

This adds an arm64 derivation to the static binary build.
```
> nix-build nix/arm64.nix
> file result/bin/conmon
result/bin/conmon: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, for GNU/Linux 2.6.32, stripped
```
Test build: [conmon.tar.gz](https://github.com/containers/conmon/files/5951723/conmon.tar.gz)
Refers to https://github.com/cri-o/cri-o/pull/4552

Add arm64 static build binary

---

src/close_fds.c

commit 0f092d5446fdadb761b8143b5c4b1d1ac9793f29 introduced the
regression.
Closes: https://github.com/containers/conmon/issues/240

close_fds: fix close of external fds

---

src/close_fds.c

in legacy exec, we send the PID back to the parent through the sync pipe fd
we can't close it before we do so.

exec: don't fail on EBADFD

---

.github/workflows/integration.yml
hack/github-actions-setup

We now add the Podman integration tests side-by-side to the CRI-O run.
This way we can ensure that changes to conmon will not negatively impact
Podman.
Some tests have to be ecluded for now, we have to dig deeper to find out
why they do not run.

Add Podman integration test GitHub action

---

hack/github-actions-setup

rc93 was released last year, makes sense to use it

ci/gha: bump runc to rc93

---

src/cgroup.c
src/cli.c
src/conmon.c
src/ctrl.c
src/utils.h

clear memory when allocated for GContext and GHashTable
check return value when we unlink (to fix one aspect that popped up in coverity scan)

some small cleanups

---

.github/workflows/integration.yml
hack/github-actions-setup
hack/kubernetes-e2e

This adds a GitHub actions test suite to run a subset of the node e2e
tests with the locally built version of conmon.

Add Kubernetes e2e tests as GitHub action

---

src/conmon.c

skip the fchmod for the standard input files when /dev/null is used.

conmon: do not chown /dev/null

---

src/conmon.c
src/ctr_exit.c
src/ctr_exit.h

Shout out to https://stackoverflow.com/questions/40311937/terminating-a-program-with-calling-atexit-functions-linux for the elegant solution.

call functions registered with atexit on SIGTERM

---

src/conmon.c
src/oom.c
src/oom.h

We don't want container runtime procesess to be unkillable
so we reset oom_score_adj back to 0 before execv
of the runtime process.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Reset OOM score back to 0 for container runtime

---

.cirrus.yml
Makefile
contrib/spec/conmon.spec.in
meson.build
nix/default-arm64.nix
nix/default.nix
src/cli.c
src/cli.h
src/conmon.c
src/conn_sock.c
src/conn_sock.h
src/ctrl.c
src/globals.c
src/globals.h
src/seccomp_notify.c
src/seccomp_notify.h
src/seccomp_notify_plugin.h

add support for seccomp notify and add a basic support for emulating
mknod and mknodat.  The handler implementation is likely going to
change, for now it is just a PoC to show how it would work.
Requires: https://github.com/containers/crun/pull/438
Requires: libseccomp-2.5

seccomp: add support for seccomp notify

---

Makefile
src/conmon.c
src/seccomp_notify.c
src/seccomp_notify.h
src/seccomp_notify_plugin.h

if seccomp version is lower than 2.5.0, then we should not compile any seccomp related things
and fail if users attempt to specify them

seccomp: fix for unsupported versions

---

Makefile
hack/seccomp-notify.sh
src/conmon.c
src/seccomp_notify.c
src/seccomp_notify.h
src/seccomp_notify_plugin.h

on older kernels we need to also check if the proper headers are installed, in addition to the seccomp version
also, unify the syntax of conditional compilation variables

Makefile: fix seccomp notify compilation issues

---

README.md

Fixes https://github.com/containers/conmon/issues/285
Seccomp is used in https://github.com/containers/conmon/blob/main/src/seccomp_notify.c#L9 but is not mentioned in the [dependencies](https://github.com/containers/conmon/blob/main/src/seccomp_notify.c#L9) section in README.

Add libseccomp to build dependency

---

src/conn_sock.c

`conmon` cannot be used to run systemd units using [`WatchdogSec=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=) because the _keep-alive ping_ is not passed along to the notify socket.
This PR adds `WATCHDOG=1` to the proxied states (in addition to `READY=1`).
What is the reason for only allowing the `READY=1` state through? Where is/should this limitation be documented?
[sd_notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html#Description) supports significantly more states of which several could be used when running within a container. What would the preferred mode of handling more states be:
* extend the list of allowed states to include all the allowed ones? 
* filter only specific states which may cause problems? `MAINPID=`? 
* …

Allow WATCHDOG=1 through the proxied systemd notify socket

---

src/ctr_exit.c

fix a race condition where all the processes spawned by the OCI
runtime are not terminated yet and reap_children() would not clean
them up.
If an --exit-delay is specified, these proceses would be left
uncleaned until the delay expires.
When used for an exec session, the zombie process would prevent the
container namespaces to be cleaned up.
Closes: https://github.com/containers/conmon/issues/290

exit: fix race zombie reaper

---

src/conmon.c

`winsz_fd_r` is always `-1` in this code path, because it will only set
in `setup_console_fifo()` which gets called a few lines below.
PTAL @haircommander

Remove unreachable code path

---

.cirrus.yml

Prior-Ubuntu support is being dropped everywhere.
Ref: https://github.com/containers/podman/issues/11070
https://github.com/containers/automation_images/pull/88
Signed-off-by: Chris Evich <cevich@redhat.com>

Cirrus: Update VM Images + Drop prior-ubuntu references

---

.github/workflows/integration.yml
runner/conmon/conmon.go
runner/conmon/options.go
runner/conmon_test/conmon_test.go
runner/conmon_test/ctr_logs_test.go
runner/conmon_test/suite_test.go
src/conmon.c
src/ctr_logging.c
src/ctr_logging.h
src/ctrl.c

when passthrough is specified, the std stream files are passed directly to the container without conmon intercepting them.

logging: new mode -l passthrough

---

src/ctr_logging.c

now, when journald is used for the log driver, the logs will appear as:
ctrName[PID]:...
or
partialID[PID]:... (if using a sufficiently old podman)
instead of
conmon[PID]

ctr_logs: use container name or ID as SYSLOG_IDENTIFIER for journald

---

src/conn_sock.c
src/ctr_exit.c
src/ctr_logging.c
src/ctr_logging.h

make sure all files under the userdata directory are closed before
calling the cleanup program.
This is needed when running on NFS since unlinking a file on NFS and
keeping it open causes a "silly rename" to keep a reference to the
file and doesn't permit rm -rf to cleanup the directory correctly.

conmon: free userdata files before exec cleanup

---

src/ctr_logging.c

if a log tag is specified, also use it for SYSLOG_IDENTIFIER.
Closes: https://github.com/containers/conmon/issues/301

logging: set SYSLOG_IDENTIFIER= with --log-tag

---

src/conmon.c

the function called is chmod but the message was referring to chown.

conmon: fix error message

---

src/ctrl.c

This causes problem that if one is closed, the glib source of the other is not removed, which causes infinite loop and 100% cpu usage.
Fixes: #167

Avoid mainfd_std{in,out} sharing the same file descriptor.

---

meson.build

We now conditionally check for the availability of `dlopen` and add `libdl` if required.
Fixes: https://github.com/containers/conmon/issues/298

Make libdl optional in meson definition

---

src/cgroup.c

In `src/cgroup.c`, the variable `memory_cgroup_file_path` is allocated with `g_build_filename()`, but it is not free'd in the error path. In the happy path, it would be properly free'd in `oom_cb_cgroup_v1()`.
Following that, in `oom_cb_cgroup_v1()` free this memory using `g_free()` instead of `free()`. Functionally, there is no difference, but semantically it's better.

fix: cgroup: Free memory_cgroup_file_path if open fails

---

src/close_fds.c
src/close_fds.h
src/ctr_exit.c

the current code that tries to list each open fd is error prone, and
it was missing "dummyfd" opened in main().  To avoid such issue, and
be future-proof, just iterate over the open file descriptors and close
them all!
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2040379

exit: close all fds >= 3

---

src/ctr_logging.c
src/ctr_stdio.c

Ensures that log lines less than or equal to 8k in size are logged as a single journald message by buffering partial messages from subsequent read calls until a newline is observed (or buffer is full).
Fixes: #242
Signed-off-by: Cory Snyder <csnyder@iland.com>

logging: buffer partial messages to journald

---

src/ctr_logging.c

The declaration of write_journal is static but the definition is
non-static, this makes the definition static too.
Signed-off-by: David Korczynski <david@adalogics.com>

logging: add missing static keyword

---

src/cli.c

https://github.com/containers/conmon/pull/342 add support for `log-global-size-max` for https://github.com/cri-o/cri-o/commit/a4080bb343acb5bfc846e576ab2783de8978b29a, but incorrectly name the CLI option as `log-size-global-max`.
Sample error message with cilium `postStop` and `preStart`:
```
[root@cp-nightsky ~]# kubectl -n kube-system describe pod cilium-rhvxd 
Name:                 cilium-rhvxd
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 cp-nightsky/147.8.202.52
Start Time:           Thu, 16 Jun 2022 01:26:46 +0000
Labels:               controller-revision-hash=b7889fb75
k8s-app=cilium
pod-template-generation=6
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status: …
```

[Fixup #342] `log-size-global-max` Should Be `log-global-size-max`

---

src/conmon.c
src/ctr_exit.c
src/ctr_exit.h

g_unix_signal_add() is implemented via an implicitly-created worker
thread in GLib.  This thread creates an eventfd, and conflicts with
conmon's general approach to taking full ownership of all open fds in
the process.
Stop using g_unix_signal_add() and switch to using g_unix_fd_add() on a
signalfd() as an alternative approach.
Fixes #330
I tested this by running
```
podman --conmon ~/src/conmon/build/conmon exec f36 sh -c 'sleep 1000&'
```
and
```
podman --conmon /usr/bin/conmon exec f36 sh -c 'sleep 1000&'
```
and suspending my laptop.  On resume, `/usr/bin/conmon` was spinning at 100% CPU, but my patched version wasn't.

Stop using g_unix_signal_add() to avoid threads

---

src/cgroup.c
src/cli.c
src/close_fds.c
src/cmsg.c
src/conmon.c
src/conn_sock.c
src/ctr_exit.c
src/oom.c
src/seccomp_notify.c
src/seccomp_notify_plugin.h
src/utils.c
src/utils.h

The main things which I changed were:
* Factor out calls to prctl so that I can replace with FreeBSD procctl
equivalents without making an ifdef mess.
* Work around the fact that FreeBSD doesn't allow chown on sockets and
non-named pipes.
* Use a different workaround for socket paths too long for sockaddr_un - the
Linux O_PATH thing was replaced with a near equivalent use of FreeBSD's
bindat.
* Some rearranging of ifdefs so that I can cut cgroups and seccomp out of the
FreeBSD build.
* Reading from pipes and/or ptys can error with EGAIN for some reason - these
calls can simply be retried similar to EINTR.
Signed-off-by: Doug Rabson <dfr@rabson.org>

Port conmon to FreeBSD

---

meson.build

meson: optionally build seccomp if it supports notify

---

.cirrus.yml

This task is absolutely critical, as despite it being replaced, conmon
is still in use by many.  Having a meta task running on important
branches is needed to maintain a functioning CI.  That said, I also
manually marked the `c6431352024203264` series images for permanent
retention as well (for the `main` branch).
Signed-off-by: Chris Evich <cevich@redhat.com>

Cirrus: Add meta task to keep CI VM images alive

---

hack/seccomp-notify.sh

On FreeBSD, this lives in /usr/local/bin. Note: this pattern is already
used for the other scripts in hack.
Signed-off-by: Doug Rabson <dfr@rabson.org>

Use /usr/bin/env to locate bash

---

src/conmon.c
src/ctr_exit.c
src/utils.c
src/utils.h

we use internally SIGUSR1 as a hack to force the check of the
container processes.
commit d91cc4321797eaa84dcfb7863e91632d2fe26861 changed the way some
signals are handled but forgot to handle SIGUSR1, so that receiving
SIGUSR1 would crash conmon.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2119072

signal: handle SIGUSR1 with signalfd

---

src/utils.c

Since kqueue treats each signal as a separate event, we need to iterate
over the signal set and add events for each.
Signed-off-by: Doug Rabson <dfr@rabson.org>

signal: Track changes to get_signal_descriptor in the FreeBSD version

---

Makefile

This avoids using install's -D flag since that does something different on FreeBSD. Also, since GNU make is called gmake on FreeBSD, we need to use $(MAKE) for sub-makes.
Signed-off-by: Doug Rabson <dfr@rabson.org>

Makefile: Fix install for FreeBSD

---

src/ctr_logging.c

msg_len doesn't take into account NUL bytes that could be present in
the buffer, while g_strdup_printf("MESSAGE=%s%s", partial_buf, buf)
does and would stop writing the string once it finds a NUL byte.  This
would lead to read after the buffer end.
Build the message string manually so that the calculated length
reflects the buffer size.
Closes: https://github.com/containers/conmon/issues/315

logging: do not read more that the buf size

---

tools/Makefile

Before GNU make 4.4, "export" variables were not actually exported to $(shell) commands, so the `export GO111MODULE=off` line had no effect. With make >= 4.4, this variable is now set in the environment of the `go build` command, which breaks it. Just remove the wrong variable assignment to have the same behavour as previously.

Fix tools/Makefile with GNU make 4.4

---

src/cgroup.c

It may be possible that the container process already got signaled but is still running, whereas we will not get an `oom` entry of `memory.events` but `oom_kill`, which provides another indicator for a possible out of memory kill.
Ref: https://www.kernel.org/doc/Documentation/cgroup-v2.txt
Fixes: https://github.com/cri-o/cri-o/issues/6580
Referring PR in conmon-rs: https://github.com/containers/conmon-rs/pull/1054

Fix OOM watcher for cgroupv2 `oom_kill` events

---

src/runtime_args.c

`--detach` is supported by both `runc` and gVisor's `runsc`, while `runsc` does not support the shorthand `-d`.
https://github.com/google/gvisor/blob/master/runsc/cmd/exec.go#L99
Without this change, `runsc` errors out on `podman exec`:
~~~
Error: OCI runtime error: runsc: flag provided but not defined: -d
~~~

Use --detach instead of -d (fix gVisor compat)

---

.packit.yaml

When "identifier" is defined, the job will be built in a dedicated Copr
project. This is a workaround for:
https://github.com/packit/packit-service/issues/1854
All rpm builds should work consistently after merging this.

packit: build in dedicated projects

---

src/cgroup.c

OpenShift 4.13 tentatively plans to use cgroupv1 on a RHEL9 era kernel, which breaks only in `PREEMPT_RT` aka `kernel-rt` due to
https://github.com/torvalds/linux/commit/2343e88d238f5de973d609d861c505890f94f22e
For now let's stumble on without oom notifications.

cgroup: Stumble on if we can't set up oom handling

---

src/conn_sock.c
src/ctr_exit.c
src/ctr_exit.h

When we create a container with crio in OKD/OCP, conmon creates a symbolic link in /var/run/crio to /run/containers/storage/overlay-containers/$cuid/userdata.
This symblic link is never removed when the container is removed, leading to several dangling symbolic links in /var/run/crio, filling up the inodes capacity in /var/run.
This PR fixes this issue by adding a function/callback to remove the symbolic link when `conmon` exits.
Refers okd-project/okd#1497 and https://issues.redhat.com/browse/OCPBUGS-7962

Fix leaking symbolic links in the opt_socket_path directory

---

src/conmon.c

Under non-reproducible circumstances it can happen that the umask of conmon is set to `0000`, which can be a security issue. To avoid that, we now use a default umask and set it directly in `main`.
We had a similar fix in CRI-O in https://github.com/cri-o/cri-o/pull/5904, but we have to do it here again because conmon is a direct parent of PID 1.
Refers to https://issues.redhat.com/browse/OCPBUGS-8057

Use default umask `0022`

---

src/ctr_exit.c

This doesn't matter since we're going to exit, but I'm sure it will show up in static analyzers.

exit: Free allocated string

---

src/ctr_logging.c

This patch improves the efficiency of the journald logging by removing the usage of /dev/null in the write_journald function.
Add a new function which directly appends the segment without flushing the buffer, so there is no need to pass a fd argument.
Another benefit is that now we get an error message instead of silently ignoring what was previously stored in the buffer.

logging: avoid opening /dev/null for each write

---

src/cmsg.c
src/ctrl.c
src/seccomp_notify.c

some issues that I've found while investigating https://github.com/containers/podman/issues/10927#issuecomment-1526019282

improve receive of terminal fd

---

src/oom.c

`attempt_oom_adjust()` takes two variables as of #392. Since both variables are used only under Linux and the compiler complains if you don't use the second one, this adds a line in to fix that.

fix compile regression on FreeBSD

---

.cirrus.yml
nix/default-ppc64le.nix

Support for building `conmon` for ppc64le architecture, based on [Add arm64 static build binary #239](https://github.com/containers/conmon/pull/239).
Reference:
The job `make bundles` fails in cri-o, due to the non availability of conmon binary for ppc64le architecture. -https://github.com/cri-o/cri-o/actions/runs/4933971318/jobs/8818878101?pr=6823 
Support cri-o for ppc64le - https://github.com/cri-o/cri-o/pull/6823
The nix build instructions had been validated locally.

Support to build conmon for ppc64le

---

.cirrus.yml
hack/github-actions-setup

Changes to update nix image to the latest stable release along with dependencies used in GH actions.

Bump nixos image and dependencies' version.

---

src/close_fds.c

While testing podman's restart policy handling, I noticed that containers which were publishing ports did not restart automatically. This was caused by conmon not properly closing the file descriptor which reserved the published port on the host before cleaning up the container. This commit lets conmon discover any extra file descriptors on FreeBSD.

Fix close_other_fds on FreeBSD

---

src/conmon.c

Since #112 the anonymous pipes are supposed to be
more permissive. Restoring the permissive state.
Close #429

Linux log fds more permissive

---

src/ctr_stdio.c

when the terminal is closed, we get EIO.  Let's treat it as a EOF.
Closes: https://github.com/containers/conmon/issues/440

stdio: ignore EIO for terminals

---

src/cli.c

Error messages should always be logged to stderr not stdout. I found this while working on:
https://github.com/containers/podman/pull/19635

cli: log parsing errors to stderr

---

src/seccomp_notify.c

Fix the following static build failure raised even when seccomp is disabled:
```
src/seccomp_notify.c:10:10: fatal error: dlfcn.h: No such file or directory
10 | #include <dlfcn.h>
|          ^~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/71b4f35b3150183c7b44bc3897f01b0019e10ebe

src/seccomp_notify.c: fix static build

---

src/conmon.c
src/ctr_exit.c
src/oom.c
src/oom.h

When the exit command is executed, the oom score is restored to its original value otherwise the command runs with -1000.
Closes: https://github.com/containers/podman/issues/20765

oom-score: restore oom score before running exit command

---

src/conn_sock.c

we hardcode `sock->buf[num_read] = '\0';` so num_read cannot be equal to the size of the buffer.

src: fix write after end of buffer

---

src/ctr_logging.c

it works in a similar way to passthrough, the only difference is that it is also allowed on a TTY.

logging: passthrough accepts a tty

---

src/conn_sock.c

Several of the standard sd-notify messages are safe to use from a container and are very useful. This commit cleans up the general handling of notify messages and allows forwarding of:
* READY=1
* RELOADING=1
* STOPPING=1
* WATCHDOG=1
* WATCHDOG=trigger
* STATUS=...
* ERRNO=...
* BUSERROR=...
* MONOTONIC_USEC...
See https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html#Well-known%20assignments for documentation of these.
Note: We don't allow unknown messages to be forewarded. For one, all the file-descriptor based ones are currently unsupported (since the forwarding doesn't handle fds), but also some options (current and future) may be security sensitive.
fixes https://github.com/containers/conmon/issues/461
fixes https://github.com/containers/conmon/issues/311

Forward more messages on the sd-notify socket

---

src/conn_sock.c
src/conn_sock.h

The change in commit 3605a368ea9c2d946e3f694c36dfc11c8e92b3d9 broke the podman test/system tests:
```
✗ [075] podman exec - cat from stdin
(from function `bail-now' in file test/system/helpers.bash, line 227,
from function `is' in file test/system/helpers.bash, line 956,
in test file test/system/075-exec.bats, line 84)
`is "${lines[0]}" "3000+0 records in"  "dd: number of records in"' failed
[11:10:24.237041104] $ /vcs/other/podman/bin/podman rm -t 0 --all --force --ignore
[11:10:24.272179180] $ /vcs/other/podman/bin/podman ps --all --external --format {{.ID}} {{.Names}}
[11:10:24.307984108] $ /vcs/other/podman/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
[11:10:24.339679735] quay.io/libpod/systemd-image:20230531 9984d4cfd1eb  quay.io/libpod/testimage:20221018 …
```

Fix podman tests

---

src/conn_sock.c
src/ctr_stdio.c

https://cov01.lab.eng.brq2.redhat.com/osh/task/342655/log/conmon-2.1.7-3.1.rhaos4.14.el9/scan-results-imp.html
(some I am not sure about how to fix)

fix some issues flagged by SAST scan

---

src/conn_sock.c

Earlier commit freed socket_parent_dir()'s result which is correct in the case it returns a path from g_build_filename, but when it returns opt_bundle_path the string should not be freed.
Make the function always return an allocated string that can be freed
Fixes: #475
Fixes: fad6bac8e65f ("fix some issues flagged by SAST scan")

Fix incorrect free in conn_sock

---

src/ctr_logging.c

When a container keeps restarting, conmon restarts and opens the log file with O_APPEND every single time, resetting bytes_written to 0 with a non-empty file.
If the container fails before writting log-size-max bytes then the log keeps growing indefinitely, potentially using up all the available space.
This should be kept in check: initialize bytes_written to the file's current size, so that it can be reset if required (it's possible that the file gets re-open before the first write if it was already above the limit, but that should almost never happen in practice)
In order to make this simpler make bytes written global variables
---- 
This bit us with podman recently with a bad container config and restart=on-failure; I thought it wasn't a problem before? but checking the code I don't …

logging: Respect log-size-max immediately after open

---

src/runtime_args.c

as gvisor doesn't use it, and runc/crun don't need it, as they'll only use it if the process args aren't defined, which conmon always does
fixes https://github.com/containers/conmon/issues/483

drop --tty on exec

---

.packit.yaml

This commit enables downstream syncing to CentOS Stream 10. The centos maintainer will need to run `packit propose-downstream` and `centpkg build` until better centos integration is in place.
The copr jobs have been split distro-wise so that Fedora and CentOS builds / tests can still be triggered automatically regardless of PR author's access to the repo, while only the RHEL jobs will need manual triggering.
EL8 jobs have also been deleted as CentOS Stream 8 will go EOL end of May and no further updates are expected to be shipped there.

Packit: enable downstream sync to CentOS Stream 10

---

Makefile

If the GOMD2MAN (environment) variable is set, then we do not need the 'docs' target to depend on 'install.tools', which will build gomd2man.
This avoids gomd2man to be build, even though the user already request the usage of a particular gomd2man binary. It also removes an implicit build dependency on go. The latter causes downstream bugs like https://bugs.gentoo.org/931645

Make 'docs' target not depend on 'install.tools' if GOMD2MAN is set

---

src/ctr_logging.c

the file is going to be removed few lines later with rename():
```
/* Replace the previous file */
if (rename(k8s_log_path_tmp, k8s_log_path) < 0) {
pexit("Failed to rename log file");
}
```
so there is no point in the expensive sync call since the file is not supposed to be persisted after a reboot.

logging: remove unuseful fsync

---

src/cgroup.c

instead use the bundle path to create the second (shurgh!) file since this is what CRI-O uses.
Closes: https://github.com/containers/conmon/issues/504

conmon: do not create oom file under cwd

---

rpm/conmon.spec

Forgot to remove it in the previous PR where crio installation was removed from rpm.

RPM: delete unnecessary patching from spec

---

docs/conmon.8.md
src/utils.c

Issue #454 is likely caused by retryable_error() not catching all possible retryable errors from the write(2) syscall.
This PR should be FeeBSD compatible. The only retriable result in question is ENOBUFS which might be bound to network latencies. Hope these are acceptable.
Signed-off-by: Jindrich Novy <jnovy@redhat.com>

Avoid bogus journal filling errors

---

src/ctr_logging.c

Make timestamp generation never fail.
If, for whatever reason, quering current time fails then the whole log message is dropped.
This PR assures the log message is not lost and the output is done with the default timestamp.

Timestamp fix

---

src/seccomp_notify.c

Users of recvfd are expected to free the `.name`.

seccomp_accept_cb: fix memory leak

---

cmd/conmon-config/conmon-config.go
go.mod
go.sum
runner/conmon/conmon.go
runner/conmon/pipes.go
runner/conmon_test/conmon_test.go
runner/conmon_test/ctr_logs_test.go
runner/conmon_test/runtime_test.go
runner/conmon_test/suite_test.go

This fixes a few minor issues with go code in this repo:
- stop using unmaintained pkg/errors (in favor of standard Go error wrapping);
- stop using deprecated io/ioutil;
- remove unused code and data;
- format octal numbers with `0o` prefix.

Modernize Go code

---

docs/conmon.8.md
src/cli.c
src/ctr_logging.c
src/ctr_logging.h

At present it's not possible to ship properly labeled logs when using podman and tools like podman-compose. Container labels are lost which makes it much harder to understand where a particular log line originated from. Log processing and analysis is significantly more inconvenient as well, because it's hard to group related logs, e.g. coming from the same compose project.
This commit implements the parts necessary to annotate log messages with container labels. Each label and value pair is specified via --log-label LABEL=VALUE arguments.
This PR was initially based on https://github.com/containers/conmon/pull/553 and ultimately was reworked enough that there's little semblance to the original PR anymore. Attribution is still preserved in commit message. The following is the changes from …

logging: Add container labels to log entries on journald

---

hack/github-actions-setup
src/ctr_logging.c

Fixes https://github.com/containers/conmon/pull/562#discussion_r2127375916
Fixes https://github.com/cri-o/cri-o/issues/9245

fix wrong conditions of k8s-file logging

---

src/ctrl.c

When multiple resize events are sent rapidly, only the first event was being processed correctly. Subsequent events in the
same buffer were ignored because `read_from_ctrl_buffer()` always processed from the beginning of the buffer instead of the current line position. This caused terminals to get stuck at incorrect dimensions, particularly during kubectl/oc debug sessions where resize events are common. The fix ensures each complete line in the control buffer is processed exactly once by passing the correct line start position to the processing function and properly null-terminating each line.

OCPBUGS-4556: src: Fix terminal resize event processing

---

runner/conmon/options.go
runner/conmon_test/k8s_log_rotation_test.go
src/ctr_logging.c

The k8s-file log driver was corrupting log entries when the log file reached max_size and needed rotation. This manifested as garbled output with repeated timestamps and broken log entries.
The root cause was in writev_buffer_flush() which incorrectly handled partial writes. When writev() returned a partial write, the function would modify the original iovec base pointers, corrupting the buffer state. During log rotation, this corrupted state would carry over to the new file descriptor, causing subsequent log entries to be malformed.
Changes:
- Simplify writev_buffer_flush() to use individual write() calls instead of complex writev() partial write handling
- Always reset buffer state after log rotation to ensure clean state with new file descriptor
- Remove conditional buffer reset that …

Fix k8s-file log corruption during log rotation

---

.packit.yaml

Without this constraint, packit triggers dup jobs for downstream updates.

Packit: constrain downstream jobs to the fedora package

---

.github/workflows/integration.yml
.github/workflows/validate.yml

See individual commits for details.
Closes: #548.

ci: use "stable" and "oldstable" Go versions

---

Makefile
nix/derivation.nix

Implement conditional systemd linking to fix static build failures. Static builds can now disable systemd with DISABLE_SYSTEMD=1. Nix derivation updated with enableSystemd parameter for flexibility. Provides backward compatibility while solving static linking issues.
Fixes: #348

Add optional systemd support for static builds

---

src/cgroup.c
test/05-oom-detection.bats

- Use separate counters for oom and oom_kill events
- Handle race condition when systemd removes cgroup
- Prevent buffer corruption in getline() usage
- Add comprehensive test coverage
Fixes: #426

Fix OOM detection on cgroup v2

---

docs/conmon.8.md
src/cli.c
src/cli.h
src/ctr_logging.c
src/ctr_logging.h
test/02-ctr-logs.bats

- Add `--no-container-partial-message` CLI option to disable CONTAINER_PARTIAL_MESSAGE=true in journald logs                                                              - This prevents splitting of long log lines into multiple journal entries
- Particularly useful for systems parsing structured logs like JSON
- Option only affects journald log driver, warns if used without journald                  
Fixes: #335

Add --no-container-partial-message option

---

src/conmon.c
test/06-exec-exit-status.bats

For exec operations, use runtime exit status instead of container status and skip runtime failure check since non-zero exit is expected behavior.
The fix addresses two core issues:
- early exit when runtime returns non-zero (treating exec failures as runtime failures)
- using container_status instead of runtime_status for final exit code determination
Fixes #328

Fix conmon exec exit status handling

---

src/cgroup.c
src/cli.c
src/conmon.c
src/conn_sock.c
src/ctr_exit.c
src/ctr_exit.h
src/ctrl.c
src/globals.h

- Fix strncpy missing null termination in conn_sock.c
- Replace malloc with g_malloc for consistency in ctr_exit.c
- Add bounds validation for sscanf parsing in ctrl.c
- Fix signal safety: change volatile pid_t to sig_atomic_t
- Add null check for cgroup2_path before use
- Clean up outdated TODO/FIXME comments
These changes address potential buffer safety, memory allocation consistency, signal safety, and logic issues flagged during code review.
Fixes: #582

Fix code quality issues

---

src/ctr_logging.c
test/09-partial-log-test.bats

Generates terminating F-sequence when container exits with partial log output.
Fixes #252

Fix missing F-sequence on container exit

---

.cirrus.yml
.gitignore
Makefile

This commit changes the `make test-binary` to recompile the conmon with `--coverage` flag so it generates the `.gcno and `.gcda` (these files are included in the `.gitignore` now) while running the tests.
After that, the `gcovr` is executed to show the code coverage based on those files.

Show the code coverage in `make test-binary` output.

---

src/conmon.c

We also fix spelling of the word "children".

Move attach start message after failure check
